"""Mysql db init

Revision ID: 468819095079
Revises: 
Create Date: 2018-06-21 22:23:52.861292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468819095079'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=150), nullable=False),
    sa.Column('user_ip', sa.String(length=15), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=150), nullable=False),
    sa.Column('user_ip', sa.String(length=15), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.Column('is_sys_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('individual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.String(length=5), nullable=False),
    sa.Column('family_id', sa.String(length=15), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'clinic_id', 'family_id', 'member_id', name='_individual_uc')
    )
    op.create_table('project_memship',
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('is_project_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('user_email', 'project_id')
    )
    op.create_table('genotype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ind_id', sa.Integer(), nullable=False),
    sa.Column('marker', sa.String(length=20), nullable=False),
    sa.Column('call_1', sa.String(length=1), nullable=False),
    sa.Column('call_2', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['ind_id'], ['individual.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ind_id', 'marker', name='_geno_uc')
    )
    op.create_table('phenotype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ind_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ind_id'], ['individual.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ind_id', 'name', name='_pheno_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phenotype')
    op.drop_table('genotype')
    op.drop_table('project_memship')
    op.drop_table('individual')
    op.drop_table('user')
    op.drop_table('system_log')
    op.drop_table('project_log')
    op.drop_table('project')
    # ### end Alembic commands ###
