"""empty message

Revision ID: eb939f97758d
Revises: 468819095079
Create Date: 2018-07-12 18:01:36.472954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb939f97758d'
down_revision = '468819095079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marker',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('chromosome', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marker_allele',
    sa.Column('marker', sa.String(length=15), nullable=False),
    sa.Column('allele', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['marker'], ['marker.id'], ),
    sa.PrimaryKeyConstraint('marker', 'allele')
    )
    op.create_foreign_key(None, 'genotype', 'marker', ['marker'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genotype', type_='foreignkey')
    op.drop_table('marker_allele')
    op.drop_table('marker')
    # ### end Alembic commands ###
